name: Deploy production
#on:
#  push:
#    branches: [main]
on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.DB_SSH_HOST }}
        username: ${{ secrets.DB_SSH_USER }}
        key: ${{ secrets.DB_SSH_KEY }}
        script: |
          cd kcidb-ng
          git pull --ff-only
          docker compose pull
          docker compose up -d --remove-orphans
